apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}
  labels:
    name: {{ .Values.serviceName }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: {{ .Values.serviceName }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      containers:
      - name: {{ .Values.serviceName }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: JAEGER_SERVICE_NAME
          value: {{ .Values.serviceName }}
        - name: JAEGER_ENDPOINT
          value: {{ .Values.jaegerEndpoint }}
        - name: PORT
          value: "80"
        - name: LOG_SEVERITY
          value: "{{ .Values.logSeverity }}"
        resources:
          requests:
            cpu: {{ .Values.cpuRequest }}
            memory: {{ .Values.memoryRequest}}
          limits:
            cpu: {{ .Values.cpuLimit }}
            memory: {{ .Values.memoryLimit }}
        ports:
        - containerPort: 80
          protocol: TCP