apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: simple-service-virtual-service
spec:
  gateways:
  - default-gateway.istio-system.svc.cluster.local
  hosts:
  - simple.bedrock.tools
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: simple-service
        port:
          number: 80
